packages:
  - packages/*

catalogs:
  better-auth:
    '@better-auth/passkey': ^1.6.9
    better-auth: ^1.6.9
  drizzle:
    drizzle-kit: ^0.31.10
    drizzle-orm: ^0.45.2
  ground0:
    '@ground0/adapter-svelte': ^0.1.2
    ground0: ^0.1.2
  wrangler:
    wrangler: ^4.87.0
  zod:
    zod: ^4.4.3

onlyBuiltDependencies:
  - esbuild
