packages:
  - packages/*

catalogs:
  better-auth:
    better-auth: ^1.4.18
  drizzle:
    drizzle-kit: ^0.31.8
    drizzle-orm: ^0.45.1
  ground0:
    '@ground0/adapter-svelte': ^0.1.2
    ground0: ^0.1.2
  wrangler:
    wrangler: ^4.60.0
  zod:
    zod: ^3.25.76

onlyBuiltDependencies:
  - esbuild
