packages:
  - packages/*

catalogs:
  better-auth:
    better-auth: ^1.4.18
    '@better-auth/passkey': ^1.4.18
  drizzle:
    drizzle-kit: ^0.31.8
    drizzle-orm: ^0.45.1
  ground0:
    '@ground0/adapter-svelte': ^0.1.2
    ground0: ^0.1.2
  build:
    wrangler: ^4.60.0
    tsdown: ^0.20.3
  zod:
    zod: ^4.3.6
  bun-types:
    bun-types: ^1.3.9
  ms:
    ms: 4.0.0-nightly.202508271359

onlyBuiltDependencies:
  - esbuild
